language: python
python:
  - 2.7
  - 3.4
  - pypy
  - pypy3
notifications:
  email: false

  # Install packages
install:
  - pip install numpy scipy matplotlib networkx nose
  - pip install --allow-all-external -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pdfminer; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install pdfminer; fi
  - pip install coveralls
 
script:
  nosetests --with-coverage --cover-package=Goulib
after_success:
  coveralls
