language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
  
before_install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib

install:
  - pip install --allow-all-external -r requirements.txt 
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=Goulib
after_success:
  coveralls
